"""FIX message encoding / decoding.

A FIX message on the wire looks like this (SOH shown as '|')::

    8=FIX.4.2|9=74|35=D|49=CLIENT|56=BROKER|34=2|52=20240101-12:00:00.000|
    11=ORD123|55=AAPL|54=1|38=100|40=2|44=150.25|10=123|

Three rules make the framing work, and getting them wrong is the classic
source of "my counterparty rejected everything" bugs:

1. **Field order is not free.**  BeginString(8), BodyLength(9) and MsgType(35)
   must be the first three fields, in that order; CheckSum(10) must be last.
   Everything in between is the "body" and is order-flexible in practice.
2. **BodyLength(9)** counts the bytes *between* the SOH that ends the
   BodyLength field and the SOH that ends the last field before CheckSum.
   It is the framing primitive: it tells the reader where the message ends
   without any escaping, because values may legally contain '=' but never SOH.
3. **CheckSum(10)** is the sum of every byte up to and including the SOH that
   precedes "10=", taken modulo 256 and rendered as exactly three digits.

This module implements those three rules and nothing else, so it works for
FIX 4.2 and 4.4 alike - the versions differ in their *dictionaries*, not in
their framing.
"""

from __future__ import annotations

import datetime as _dt

SOH = "\x01"          # the real field separator on the wire
PIPE = "|"            # human readable stand-in used in logs and fixtures

# Fields that are structural rather than content; they are generated by
# encode() and must never be carried around in the body.
_FRAMING_TAGS = (8, 9, 10)


class FixParseError(ValueError):
    """Raised when a byte string is not a well-formed FIX message."""


def utc_timestamp(when: _dt.datetime | None = None) -> str:
    """Return a FIX UTCTimestamp: ``YYYYMMDD-HH:MM:SS.sss`` (millisecond
    precision, always UTC - FIX has no concept of local time)."""
    when = when or _dt.datetime.now(_dt.timezone.utc)
    return when.strftime("%Y%m%d-%H:%M:%S.") + f"{when.microsecond // 1000:03d}"


def format_decimal(value) -> str:
    """Render a FIX Qty/Price field without a spurious trailing ``.0``.

    FIX numbers are decimal *strings*, and counterparties compare them as text
    during reconciliation, so "100" and "100.0" are not interchangeable even
    though they are numerically equal.  Non-numeric input is passed through
    untouched so callers can send a value verbatim when they need to.
    """
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if number == int(number):
        return str(int(number))
    return f"{number:g}"


class FixMessage:
    """An ordered collection of (tag, value) pairs.

    Order is preserved because FIX repeating groups are positional: the fields
    of the second group entry follow the fields of the first, and reordering
    them changes the meaning of the message.
    """

    __slots__ = ("fields",)

    def __init__(self, fields=None):
        self.fields: list[tuple[int, str]] = []
        if fields:
            for tag, value in fields:
                self.set(tag, value)

    # -- construction -------------------------------------------------------
    def set(self, tag: int, value) -> "FixMessage":
        """Append a field.  Returns self so calls can be chained."""
        if value is None:
            return self
        self.fields.append((int(tag), str(value)))
        return self

    def set_many(self, pairs) -> "FixMessage":
        for tag, value in pairs:
            self.set(tag, value)
        return self

    # -- access -------------------------------------------------------------
    def get(self, tag: int, default=None):
        """First value for ``tag`` (FIX semantics: header fields appear once)."""
        for t, v in self.fields:
            if t == tag:
                return v
        return default

    def get_all(self, tag: int) -> list[str]:
        """Every value for ``tag`` - needed inside repeating groups."""
        return [v for t, v in self.fields if t == tag]

    def get_int(self, tag: int, default=None):
        raw = self.get(tag)
        return default if raw is None else int(raw)

    def get_float(self, tag: int, default=None):
        raw = self.get(tag)
        return default if raw is None else float(raw)

    def __contains__(self, tag: int) -> bool:
        return any(t == tag for t, _ in self.fields)

    @property
    def msg_type(self) -> str | None:
        return self.get(35)

    # -- serialisation ------------------------------------------------------
    def encode(self, begin_string: str = "FIX.4.2") -> bytes:
        """Render the message to wire bytes, computing 9 and 10 for us.

        The body is everything except the framing tags; MsgType(35) is lifted
        to the front of the body so it lands in the spec-mandated position.
        """
        body_fields = [(t, v) for t, v in self.fields if t not in _FRAMING_TAGS]
        msg_type = next((v for t, v in body_fields if t == 35), None)
        if msg_type is None:
            raise FixParseError("cannot encode a message without MsgType (35)")
        ordered = [(35, msg_type)] + [(t, v) for t, v in body_fields if t != 35]

        body = "".join(f"{t}={v}{SOH}" for t, v in ordered)
        head = f"8={begin_string}{SOH}9={len(body.encode())}{SOH}"

        # Checksum covers the header and body but not itself.
        prefix = (head + body).encode()
        checksum = sum(prefix) % 256
        return prefix + f"10={checksum:03d}{SOH}".encode()

    # -- parsing ------------------------------------------------------------
    @classmethod
    def decode(cls, raw: bytes | str, validate_checksum: bool = True) -> "FixMessage":
        """Parse wire bytes into a :class:`FixMessage`.

        Accepts pipe-delimited text too, which makes test fixtures readable.
        """
        if isinstance(raw, bytes):
            text = raw.decode("latin-1")
        else:
            text = raw
        if SOH not in text and PIPE in text:
            text = text.replace(PIPE, SOH)

        if validate_checksum:
            _verify_checksum(text)

        msg = cls()
        for chunk in text.split(SOH):
            if not chunk:
                continue
            tag, sep, value = chunk.partition("=")
            if not sep:
                raise FixParseError(f"field without '=': {chunk!r}")
            try:
                msg.fields.append((int(tag), value))
            except ValueError:
                raise FixParseError(f"non-numeric tag: {tag!r}") from None
        if not msg.fields:
            raise FixParseError("empty message")
        return msg

    # -- presentation -------------------------------------------------------
    def to_pipe(self) -> str:
        """``8=FIX.4.2|35=D|11=ORD123|...`` - the canonical way FIX is shown
        in logs, support tickets and specifications."""
        return "".join(f"{t}={v}{PIPE}" for t, v in self.fields)

    def __str__(self) -> str:
        return self.to_pipe()

    def __repr__(self) -> str:
        return f"<FixMessage 35={self.msg_type} {self.to_pipe()}>"

    def __eq__(self, other) -> bool:
        return isinstance(other, FixMessage) and self.fields == other.fields


def _verify_checksum(text: str) -> None:
    """Validate tag 10 if present.  A bad checksum means the stream is
    corrupt or misframed, and the session must not act on the message."""
    marker = f"{SOH}10="
    idx = text.rfind(marker)
    if idx == -1:
        return  # no trailer yet (partial message) - framing layer will catch it
    covered = text[: idx + 1].encode("latin-1")
    stated = text[idx + len(marker):].rstrip(SOH)
    expected = f"{sum(covered) % 256:03d}"
    if stated != expected:
        raise FixParseError(f"checksum mismatch: stated {stated}, computed {expected}")


class FixStreamReader:
    """Reassembles FIX messages from an arbitrarily chunked TCP byte stream.

    TCP is a stream, not a datagram service: one ``recv()`` may return half a
    message, or three and a half messages.  Every real FIX engine needs this
    layer.  We frame on BodyLength(9) rather than scanning for a terminator,
    exactly as the specification intends.
    """

    def __init__(self):
        self._buffer = bytearray()

    def feed(self, data: bytes) -> list[FixMessage]:
        """Add received bytes; return every *complete* message now available."""
        self._buffer.extend(data)
        out = []
        while True:
            frame = self._take_one()
            if frame is None:
                return out
            out.append(FixMessage.decode(frame))

    @property
    def pending(self) -> bytes:
        """Bytes buffered so far that do not yet form a complete message."""
        return bytes(self._buffer)

    def _take_one(self) -> bytes | None:
        buf = self._buffer

        # Resynchronise: discard anything before the next "8=" BeginString.
        start = buf.find(b"8=")
        if start == -1:
            return None
        if start > 0:
            del buf[:start]

        # BodyLength is the second field, so look for the SOH-prefixed "9=".
        len_at = buf.find(b"\x019=")
        if len_at == -1:
            return None
        digits_at = len_at + 3
        end_of_len = buf.find(b"\x01", digits_at)
        if end_of_len == -1:
            return None
        try:
            body_length = int(buf[digits_at:end_of_len])
        except ValueError:
            raise FixParseError("BodyLength (9) is not an integer") from None

        body_start = end_of_len + 1
        body_end = body_start + body_length
        # The trailer is fixed width: "10=" + 3 digits + SOH == 7 bytes.
        total = body_end + 7
        if len(buf) < total:
            return None  # message still in flight

        frame = bytes(buf[:total])
        del buf[:total]
        return frame
